package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

@Data
@ApiModel
public class Addr implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="userId", notes="", example="", position=100)
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.address
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="address", notes="", example="address", position=100)
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.address2
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="address2", notes="", example="address2", position=100)
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.city
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="city", notes="", example="city", position=100)
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.country
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="country", notes="", example="country", position=100)
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.zip_code
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="zipCode", notes="", example="zipCode", position=100)
    private String zipCode;
}