package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

@Data
@ApiModel
public class Contract implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="userId", notes="", example="", position=100)
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.email
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="email", notes="", example="email", position=100)
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.phone
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="phone", notes="", example="phone", position=100)
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.skype
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="skype", notes="", example="skype", position=100)
    private String skype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.facebook
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="facebook", notes="", example="facebook", position=100)
    private String facebook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.linkedin
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="linkedin", notes="", example="linkedin", position=100)
    private String linkedin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.website
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="website", notes="", example="website", position=100)
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.note
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="note", notes="", example="note", position=100)
    private String note;
}