package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

@Data
@ApiModel
public class PermRole implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm_role.permission_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="permissionId", notes="", example="", position=100)
    private Long permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm_role.role_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="roleId", notes="", example="", position=100)
    private Long roleId;
}