package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

@Data
@ApiModel
public class PermInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="id", notes="", example="", position=100)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.permission
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="permission", notes="", example="permission", position=100)
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.enabled
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="enabled", notes="", example="", position=100)
    private Integer enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.note
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="note", notes="", example="note", position=100)
    private String note;
}