package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
@ApiModel
public class RoleInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="id", notes="", example="", position=100)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="name", notes="角色名称", example="角色名称", position=100)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="createTime", notes="创建时间", example="2022-08-11 17:08:22", position=100)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.update_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="updateTime", notes="更新时间", example="2022-08-11 17:08:22", position=100)
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.status
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="status", notes="状态 0停用 1启用", example="", position=100)
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.parent_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="parentId", notes="父角色id", example="", position=100)
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="desc", notes="角色描述", example="角色描述", position=100)
    private String desc;
}