package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

@Data
@ApiModel
public class RoleInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="id", notes="", example="", position=100)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="role", notes="", example="role", position=100)
    private String role;
}