package com.panda.auth.user.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
@ApiModel
public class UserInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="id", notes="", example="", position=100)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.username
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="username", notes="", example="username", position=100)
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="password", notes="", example="password", position=100)
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="name", notes="", example="name", position=100)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.surname
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="surname", notes="", example="surname", position=100)
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.gender
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="gender", notes="", example="", position=100)
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.birth_date
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="birthDate", notes="", example="2022-08-09 14:35:22", position=100)
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.enabled
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="enabled", notes="", example="", position=100)
    private Byte enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.creation_dt
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="creationDt", notes="", example="2022-08-09 14:35:22", position=100)
    private Date creationDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.updated_dt
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="updatedDt", notes="", example="2022-08-09 14:35:22", position=100)
    private Date updatedDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_dt
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="loginDt", notes="", example="2022-08-09 14:35:22", position=100)
    private Date loginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.note
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="note", notes="", example="note", position=100)
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.secured
     *
     * @mbg.generated
     */
    @ApiModelProperty(name="secured", notes="", example="", position=100)
    private Byte secured;
}