spring:
  application:
    # 应用名称
    name: panda-auth
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8888


# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug