spring:
  application:
    name: spring-gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/panda_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
    # 应用名称
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        port: 8721
        dashboard: 127.0.0.1:8081
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true

server:
  port: 9000
  ssl:
    enable: false
    key-store: classpath:flybabycat-cn-tomcat-0808180015.jks
    key-store-password:
    key-store-type: JKS


# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug