spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/panda_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        ###服务注册地址
        server-addr: localhost:8848
      config:
        file-extension: yaml #文件后缀名

server:
  port: 8081

test:
  conf: jsklafjds